spring:
  application:
    name: furbaby-inn
  datasource:
    url: jdbc:mysql://localhost:3306/furbaby_inn?useUnicode=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接池配置
  hikari:
     # 最小空闲连接数。连接池中维护的最小空闲连接数，即使没有活动，也会保留这么多连接。
     minimum-idle: 5
     # 最大连接池大小。连接池中允许的最大连接数，包括空闲和正在使用的连接。
     maximum-pool-size: 20
     # 空闲连接超时时间。当连接池中的连接空闲时间超过此值时，它将被标记为可回收。单位是毫秒 (300000ms = 5分钟)。
     idle-timeout: 300000
     # 连接最大生命周期。连接池中连接的最长生命周期，超过此时间的连接将被关闭并替换。这有助于防止内存泄漏。单位是毫秒 (1200000ms = 20分钟)。
     max-lifetime: 1200000
     # 连接超时时间。客户端等待从池中获取连接的最长时间。如果在此时间内没有可用连接，则会抛出SQLException。单位是毫秒 (30000ms = 30秒)。
     connection-timeout: 30000

jwt:
#  Keys.hmacShaKeyFor 报错：如果你的 secret 长度小于 32 字节（即少于 32 个字符），启动会报 weak key 异常。
#  解决：密钥设置成 32 位以上，或使用 Base64 编码的字符串。
#
#  Token 放在 Header 里的格式：通常前端传的是 Authorization: Bearer <token>。
#  如果要兼容这种写法，拦截器里拿到 token 后需要去掉 Bearer 前缀

  # 密钥（务必足够长，至少32个字符，生产中建议使用 Base64 编码的复杂字符串），这里使用测试用的密钥（FurbabyJwtSecretKey2026YYYWork）进行base64编码来测试
  secret: "RnVyYmFieUp3dFNlY3JldEtleTIwMjZZWVlXb3Jr"
  # 过期时间（毫秒），例如 7天 = 7 * 24 * 60 * 60 * 1000
  expiration: 604800000

mybatis-plus:
  configuration:
    # 开启枚举映射处理器，实现枚举型数据对数据库的映射，插入数据枚举类型转换为数据库中的
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  type-enums-package: com.furbaby.furbaby.enums

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
